import '../models/game_result.dart';
import '../services/myrient_service.dart';
export '../models/game_result.dart';

/// Abstract provider interface
abstract class SearchProvider {
  String get name;
  Future<List<GameResult>> search(String query, {String? platform});
}

/// Unified Storefront that aggregates all providers
class DiscoveryStorefront {
  final List<SearchProvider> _providers = [];

  void registerProvider(SearchProvider provider) {
    _providers.add(provider);
  }

  /// Search all providers in parallel and merge results
  Future<List<GameResult>> search(String query, {String? platform}) async {
    final futures = _providers.map((p) => p.search(query, platform: platform));
    final results = await Future.wait(futures, eagerError: false);

    // Flatten and sort by relevance (title match)
    final merged = results.expand((r) => r).toList();
    merged.sort((a, b) {
      // Prioritize exact title matches
      final aScore =
          a.title.toLowerCase().startsWith(query.toLowerCase()) ? 0 : 1;
      final bScore =
          b.title.toLowerCase().startsWith(query.toLowerCase()) ? 0 : 1;
      return aScore.compareTo(bScore);
    });

    return merged;
  }

  /// Helper to generate GameTDB cover URLs
  static String _gameTDBCover(String gameId, String platform) {
    final p = platform.toLowerCase();
    if (p.contains('wii u') || p == 'wiiu') {
      return 'https://art.gametdb.com/wiiu/cover3D/US/$gameId.png';
    } else if (p.contains('gamecube') || p == 'gc') {
      return 'https://art.gametdb.com/wii/cover3D/US/$gameId.png';
    }
    return 'https://art.gametdb.com/wii/cover3D/US/$gameId.png';
  }

  // Myrient base URLs for direct downloads
  static const String _myrientWiiRvz = 'https://myrient.erista.me/files/Redump/Nintendo%20-%20Wii%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D/';
  static const String _myrientGcRvz = 'https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D/';
  static const String _myrientWiiU = 'https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Wii%20U%20(Digital)%20(CDN)/';
  static const String _myrientGba = 'https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance/';
  static const String _myrientN64 = 'https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%2064%20(BigEndian)/';
  static const String _myrientSnes = 'https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/';
  static const String _myrientNes = 'https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20(Headered)/';
  static const String _myrientGenesis = 'https://myrient.erista.me/files/No-Intro/Sega%20-%20Mega%20Drive%20-%20Genesis/';
  static const String _myrientNds = 'https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%20DS%20(Decrypted)/';
  static const String _myrientPsp = 'https://myrient.erista.me/files/Redump/Sony%20-%20PlayStation%20Portable/';
  static const String _myrientPs1 = 'https://myrient.erista.me/files/Redump/Sony%20-%20PlayStation/';

  /// Get popular featured games for all platforms - using DIRECT Myrient download URLs
  List<GameResult> getPopularGames() {
    return [
      // === WII GAMES (RVZ format from Myrient) ===
      GameResult(
        title: 'Mario Kart Wii (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientWiiRvz}Mario%20Kart%20Wii%20(USA)%20(En,Fr,Es).zip',
        downloadUrl: '${_myrientWiiRvz}Mario%20Kart%20Wii%20(USA)%20(En,Fr,Es).zip',
        requiresBrowser: false,
        gameId: 'RMCE01',
        fileSizeMb: 2700,
        size: '2.7 GB',
        format: 'ZIP',
        coverUrl: _gameTDBCover('RMCE01', 'Wii'),
        description: 'Race against friends and foes in the ultimate kart racing experience on Wii.',
      ),
      GameResult(
        title: 'Super Mario Galaxy (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientWiiRvz}Super%20Mario%20Galaxy%20(USA)%20(En,Fr,Es).zip',
        downloadUrl: '${_myrientWiiRvz}Super%20Mario%20Galaxy%20(USA)%20(En,Fr,Es).zip',
        requiresBrowser: false,
        gameId: 'RMGE01',
        fileSizeMb: 3300,
        size: '3.3 GB',
        format: 'ZIP',
        coverUrl: _gameTDBCover('RMGE01', 'Wii'),
        description: 'Embark on a cosmic adventure through galaxies in this groundbreaking 3D platformer.',
      ),
      GameResult(
        title: 'New Super Mario Bros. Wii (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientWiiRvz}New%20Super%20Mario%20Bros.%20Wii%20(USA)%20(En,Fr,Es)%20(Rev%202).zip',
        downloadUrl: '${_myrientWiiRvz}New%20Super%20Mario%20Bros.%20Wii%20(USA)%20(En,Fr,Es)%20(Rev%202).zip',
        requiresBrowser: false,
        gameId: 'SMNE01',
        fileSizeMb: 420,
        size: '420 MB',
        format: 'ZIP',
        coverUrl: _gameTDBCover('SMNE01', 'Wii'),
        description: 'Classic side-scrolling Mario action with up to 4 players simultaneously.',
      ),
      GameResult(
        title: 'Wii Sports (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientWiiRvz}Wii%20Sports%20(USA)%20(Rev%201).zip',
        downloadUrl: '${_myrientWiiRvz}Wii%20Sports%20(USA)%20(Rev%201).zip',
        requiresBrowser: false,
        gameId: 'RSPE01',
        fileSizeMb: 420,
        size: '420 MB',
        format: 'ZIP',
        coverUrl: _gameTDBCover('RSPE01', 'Wii'),
        description: 'The iconic game that brought motion controls to the masses with tennis, bowling, golf and more.',
      ),
      GameResult(
        title: 'Legend of Zelda: Twilight Princess (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientWiiRvz}Legend%20of%20Zelda%2C%20The%20-%20Twilight%20Princess%20(USA).zip',
        downloadUrl: '${_myrientWiiRvz}Legend%20of%20Zelda%2C%20The%20-%20Twilight%20Princess%20(USA).zip',
        requiresBrowser: false,
        gameId: 'RZDE01',
        fileSizeMb: 1400,
        size: '1.4 GB',
        format: 'ZIP',
        coverUrl: _gameTDBCover('RZDE01', 'Wii'),
        description: 'Link embarks on his darkest adventure yet in this epic action-adventure.',
      ),
      GameResult(
        title: 'Super Smash Bros. Brawl (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientWiiRvz}Super%20Smash%20Bros.%20Brawl%20(USA)%20(Rev%201).zip',
        downloadUrl: '${_myrientWiiRvz}Super%20Smash%20Bros.%20Brawl%20(USA)%20(Rev%201).zip',
        requiresBrowser: false,
        gameId: 'RSBE01',
        fileSizeMb: 2500,
        size: '2.5 GB',
        format: 'ZIP',
        coverUrl: _gameTDBCover('RSBE01', 'Wii'),
        description: 'Nintendo all-stars battle it out in the ultimate crossover fighting game.',
      ),
      GameResult(
        title: 'Metroid Prime 3: Corruption (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientWiiRvz}Metroid%20Prime%203%20-%20Corruption%20(USA).zip',
        downloadUrl: '${_myrientWiiRvz}Metroid%20Prime%203%20-%20Corruption%20(USA).zip',
        requiresBrowser: false,
        gameId: 'RM3E01',
        fileSizeMb: 1700,
        size: '1.7 GB',
        format: 'ZIP',
        coverUrl: _gameTDBCover('RM3E01', 'Wii'),
        description: 'Samus faces her greatest threat in this epic conclusion to the Prime trilogy.',
      ),
      GameResult(
        title: 'Donkey Kong Country Returns (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientWiiRvz}Donkey%20Kong%20Country%20Returns%20(USA)%20(En,Fr,Es)%20(Rev%201).zip',
        downloadUrl: '${_myrientWiiRvz}Donkey%20Kong%20Country%20Returns%20(USA)%20(En,Fr,Es)%20(Rev%201).zip',
        requiresBrowser: false,
        gameId: 'SF8E01',
        fileSizeMb: 1800,
        size: '1.8 GB',
        format: 'ZIP',
        coverUrl: _gameTDBCover('SF8E01', 'Wii'),
        description: 'DK and Diddy swing back into action in this challenging platformer.',
      ),

      // === GAMECUBE GAMES (RVZ format from Myrient) ===
      GameResult(
        title: 'Super Smash Bros. Melee (USA)',
        platform: 'GameCube',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGcRvz}Super%20Smash%20Bros.%20Melee%20(USA)%20(En,Ja)%20(Rev%202).zip',
        downloadUrl: '${_myrientGcRvz}Super%20Smash%20Bros.%20Melee%20(USA)%20(En,Ja)%20(Rev%202).zip',
        requiresBrowser: false,
        gameId: 'GALE01',
        fileSizeMb: 500,
        size: '500 MB',
        format: 'ZIP',
        coverUrl: _gameTDBCover('GALE01', 'GameCube'),
        description: 'The legendary fighting game that started a competitive phenomenon.',
      ),
      GameResult(
        title: 'Legend of Zelda: Wind Waker (USA)',
        platform: 'GameCube',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGcRvz}Legend%20of%20Zelda%2C%20The%20-%20The%20Wind%20Waker%20(USA%2C%20Canada).zip',
        downloadUrl: '${_myrientGcRvz}Legend%20of%20Zelda%2C%20The%20-%20The%20Wind%20Waker%20(USA%2C%20Canada).zip',
        requiresBrowser: false,
        gameId: 'GZLE01',
        fileSizeMb: 550,
        size: '550 MB',
        format: 'RVZ',
        coverUrl: _gameTDBCover('GZLE01', 'GameCube'),
        description: 'Set sail across a vast ocean in this cel-shaded Zelda adventure.',
      ),
      GameResult(
        title: 'Mario Kart: Double Dash!! (USA)',
        platform: 'GameCube',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGcRvz}Mario%20Kart%20-%20Double%20Dash!!%20(USA).rvz',
        downloadUrl: '${_myrientGcRvz}Mario%20Kart%20-%20Double%20Dash!!%20(USA).rvz',
        requiresBrowser: false,
        gameId: 'GM4E01',
        fileSizeMb: 550,
        size: '550 MB',
        format: 'RVZ',
        coverUrl: _gameTDBCover('GM4E01', 'GameCube'),
        description: 'Two drivers, one kart! The most unique Mario Kart experience.',
      ),
      GameResult(
        title: 'Super Mario Sunshine (USA)',
        platform: 'GameCube',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGcRvz}Super%20Mario%20Sunshine%20(USA).rvz',
        downloadUrl: '${_myrientGcRvz}Super%20Mario%20Sunshine%20(USA).rvz',
        requiresBrowser: false,
        gameId: 'GMSE01',
        fileSizeMb: 550,
        size: '550 MB',
        format: 'RVZ',
        coverUrl: _gameTDBCover('GMSE01', 'GameCube'),
        description: 'Mario cleans up Isle Delfino with his trusty water pack FLUDD.',
      ),
      GameResult(
        title: 'Metroid Prime (USA)',
        platform: 'GameCube',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGcRvz}Metroid%20Prime%20(USA).rvz',
        downloadUrl: '${_myrientGcRvz}Metroid%20Prime%20(USA).rvz',
        requiresBrowser: false,
        gameId: 'GM8E01',
        fileSizeMb: 550,
        size: '550 MB',
        format: 'RVZ',
        coverUrl: _gameTDBCover('GM8E01', 'GameCube'),
        description: 'Samus Aran\'s first-person adventure that redefined the franchise.',
      ),
      GameResult(
        title: 'Paper Mario: Thousand-Year Door (USA)',
        platform: 'GameCube',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGcRvz}Paper%20Mario%20-%20The%20Thousand-Year%20Door%20(USA).rvz',
        downloadUrl: '${_myrientGcRvz}Paper%20Mario%20-%20The%20Thousand-Year%20Door%20(USA).rvz',
        requiresBrowser: false,
        gameId: 'G8ME01',
        fileSizeMb: 550,
        size: '550 MB',
        format: 'RVZ',
        coverUrl: _gameTDBCover('G8ME01', 'GameCube'),
        description: 'The beloved RPG where Mario flattens his way through a charming story.',
      ),
      GameResult(
        title: 'Luigi\'s Mansion (USA)',
        platform: 'GameCube',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGcRvz}Luigi%27s%20Mansion%20(USA).rvz',
        downloadUrl: '${_myrientGcRvz}Luigi%27s%20Mansion%20(USA).rvz',
        requiresBrowser: false,
        gameId: 'GLME01',
        fileSizeMb: 1100,
        size: '1.1 GB',
        coverUrl: _gameTDBCover('GLME01', 'GameCube'),
        description: 'Luigi hunts ghosts with his Poltergust 3000 in his first solo adventure.',
      ),
      GameResult(
        title: 'F-Zero GX (USA)',
        platform: 'GameCube',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGcRvz}F-Zero%20GX%20(USA).rvz',
        downloadUrl: '${_myrientGcRvz}F-Zero%20GX%20(USA).rvz',
        requiresBrowser: false,
        gameId: 'GFZE01',
        fileSizeMb: 550,
        size: '550 MB',
        format: 'RVZ',
        coverUrl: _gameTDBCover('GFZE01', 'GameCube'),
        description: 'Blistering fast futuristic racing at 60fps - the ultimate F-Zero.',
      ),

      // === WII U GAMES (Note: Wii U downloads require Cemu emulator) ===
      GameResult(
        title: 'Mario Kart 8 (USA)',
        platform: 'Wii U',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientWiiU}Mario%20Kart%208%20(USA).wux',
        downloadUrl: '${_myrientWiiU}Mario%20Kart%208%20(USA).wux',
        requiresBrowser: false,
        gameId: 'AMKE01',
        fileSizeMb: 5300,
        size: '5.3 GB',
        format: 'WUX',
        coverUrl: _gameTDBCover('AMKE01', 'Wii U'),
        description: 'Anti-gravity kart racing with stunning HD visuals and 48 tracks.',
      ),
      GameResult(
        title: 'Super Smash Bros. for Wii U (USA)',
        platform: 'Wii U',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientWiiU}Super%20Smash%20Bros.%20for%20Wii%20U%20(USA).wux',
        downloadUrl: '${_myrientWiiU}Super%20Smash%20Bros.%20for%20Wii%20U%20(USA).wux',
        requiresBrowser: false,
        gameId: 'AXFE01',
        fileSizeMb: 15600,
        size: '15.6 GB',
        format: 'WUX',
        coverUrl: _gameTDBCover('AXFE01', 'Wii U'),
        description: 'The ultimate Smash experience with 58 fighters and 8-player battles.',
      ),
      GameResult(
        title: 'Legend of Zelda: Breath of the Wild (USA)',
        platform: 'Wii U',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientWiiU}Legend%20of%20Zelda%2C%20The%20-%20Breath%20of%20the%20Wild%20(USA).wux',
        downloadUrl: '${_myrientWiiU}Legend%20of%20Zelda%2C%20The%20-%20Breath%20of%20the%20Wild%20(USA).wux',
        requiresBrowser: false,
        gameId: 'ALZE01',
        fileSizeMb: 13000,
        size: '13.0 GB',
        format: 'WUX',
        coverUrl: _gameTDBCover('ALZE01', 'Wii U'),
        description: 'Explore a vast open world in this revolutionary Zelda adventure.',
      ),
      GameResult(
        title: 'Super Mario 3D World (USA)',
        platform: 'Wii U',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientWiiU}Super%20Mario%203D%20World%20(USA).wux',
        downloadUrl: '${_myrientWiiU}Super%20Mario%203D%20World%20(USA).wux',
        requiresBrowser: false,
        gameId: 'ARDE01',
        fileSizeMb: 1700,
        size: '1.7 GB',
        format: 'WUX',
        coverUrl: _gameTDBCover('ARDE01', 'Wii U'),
        description: 'Four-player 3D platforming fun with the cat suit power-up.',
      ),
      GameResult(
        title: 'Splatoon (USA)',
        platform: 'Wii U',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientWiiU}Splatoon%20(USA).wux',
        downloadUrl: '${_myrientWiiU}Splatoon%20(USA).wux',
        requiresBrowser: false,
        gameId: 'AGME01',
        fileSizeMb: 1900,
        size: '1.9 GB',
        format: 'WUX',
        coverUrl: _gameTDBCover('AGME01', 'Wii U'),
        description: 'Ink-splattering team battles in this unique multiplayer shooter.',
      ),
      GameResult(
        title: 'Bayonetta 2 (USA)',
        platform: 'Wii U',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientWiiU}Bayonetta%202%20(USA).wux',
        downloadUrl: '${_myrientWiiU}Bayonetta%202%20(USA).wux',
        requiresBrowser: false,
        gameId: 'AQUE01',
        fileSizeMb: 14200,
        size: '14.2 GB',
        format: 'WUX',
        coverUrl: _gameTDBCover('AQUE01', 'Wii U'),
        description: 'Stylish action as the Umbra Witch returns with intense combat.',
      ),
      GameResult(
        title: 'Xenoblade Chronicles X (USA)',
        platform: 'Wii U',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientWiiU}Xenoblade%20Chronicles%20X%20(USA).wux',
        downloadUrl: '${_myrientWiiU}Xenoblade%20Chronicles%20X%20(USA).wux',
        requiresBrowser: false,
        gameId: 'AX5E01',
        fileSizeMb: 22800,
        size: '22.8 GB',
        format: 'WUX',
        coverUrl: _gameTDBCover('AX5E01', 'Wii U'),
        description: 'Explore a massive alien planet with mechs in this open-world RPG.',
      ),
      GameResult(
        title: 'Pikmin 3 (USA)',
        platform: 'Wii U',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientWiiU}Pikmin%203%20(USA).wux',
        downloadUrl: '${_myrientWiiU}Pikmin%203%20(USA).wux',
        requiresBrowser: false,
        gameId: 'AC3E01',
        fileSizeMb: 3200,
        size: '3.2 GB',
        format: 'WUX',
        coverUrl: _gameTDBCover('AC3E01', 'Wii U'),
        description: 'Command an army of tiny Pikmin to solve puzzles and battle creatures.',
      ),

      // === RETRO: GBA GAMES (Direct Myrient Downloads) ===
      GameResult(
        title: 'Pokemon Emerald (USA)',
        platform: 'GBA',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGba}Pokemon%20-%20Emerald%20Version%20(USA%2C%20Europe).zip',
        downloadUrl: '${_myrientGba}Pokemon%20-%20Emerald%20Version%20(USA%2C%20Europe).zip',
        requiresBrowser: false,
        gameId: 'BPEE',
        fileSizeMb: 16,
        size: '16 MB',
        format: 'ZIP',
        description: 'The definitive Gen 3 Pokemon experience with the Battle Frontier.',
      ),
      GameResult(
        title: 'Pokemon FireRed (USA)',
        platform: 'GBA',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGba}Pokemon%20-%20FireRed%20Version%20(USA%2C%20Europe)%20(Rev%201).zip',
        downloadUrl: '${_myrientGba}Pokemon%20-%20FireRed%20Version%20(USA%2C%20Europe)%20(Rev%201).zip',
        requiresBrowser: false,
        gameId: 'BPRE',
        fileSizeMb: 16,
        size: '16 MB',
        format: 'ZIP',
        description: 'Relive the Kanto adventure in this enhanced remake of Pokemon Red.',
      ),
      GameResult(
        title: 'Legend of Zelda: Minish Cap (USA)',
        platform: 'GBA',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGba}Legend%20of%20Zelda%2C%20The%20-%20The%20Minish%20Cap%20(USA).zip',
        downloadUrl: '${_myrientGba}Legend%20of%20Zelda%2C%20The%20-%20The%20Minish%20Cap%20(USA).zip',
        requiresBrowser: false,
        gameId: 'BZME',
        fileSizeMb: 16,
        size: '16 MB',
        format: 'ZIP',
        description: 'Link shrinks down to help the Picori in this charming adventure.',
      ),
      GameResult(
        title: 'Metroid Fusion (USA)',
        platform: 'GBA',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGba}Metroid%20Fusion%20(USA).zip',
        downloadUrl: '${_myrientGba}Metroid%20Fusion%20(USA).zip',
        requiresBrowser: false,
        gameId: 'AMTE',
        fileSizeMb: 8,
        size: '8 MB',
        format: 'ZIP',
        description: 'Samus battles the X parasites in this tense, story-driven adventure.',
      ),
      GameResult(
        title: 'Metroid Zero Mission (USA)',
        platform: 'GBA',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGba}Metroid%20-%20Zero%20Mission%20(USA).zip',
        downloadUrl: '${_myrientGba}Metroid%20-%20Zero%20Mission%20(USA).zip',
        requiresBrowser: false,
        gameId: 'BMXE',
        fileSizeMb: 8,
        size: '8 MB',
        format: 'ZIP',
        description: 'The original Metroid remade with modern gameplay and new content.',
      ),
      GameResult(
        title: 'Fire Emblem (USA)',
        platform: 'GBA',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGba}Fire%20Emblem%20(USA%2C%20Australia).zip',
        downloadUrl: '${_myrientGba}Fire%20Emblem%20(USA%2C%20Australia).zip',
        requiresBrowser: false,
        gameId: 'AFEE',
        fileSizeMb: 16,
        size: '16 MB',
        format: 'ZIP',
        description: 'The first Fire Emblem released in the West, featuring tactical RPG battles.',
      ),
      GameResult(
        title: 'Fire Emblem: Sacred Stones (USA)',
        platform: 'GBA',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGba}Fire%20Emblem%20-%20The%20Sacred%20Stones%20(USA%2C%20Australia).zip',
        downloadUrl: '${_myrientGba}Fire%20Emblem%20-%20The%20Sacred%20Stones%20(USA%2C%20Australia).zip',
        requiresBrowser: false,
        gameId: 'BE8E',
        fileSizeMb: 16,
        size: '16 MB',
        format: 'ZIP',
        description: 'A standalone Fire Emblem with branching promotions and world map.',
      ),
      GameResult(
        title: 'Golden Sun (USA)',
        platform: 'GBA',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGba}Golden%20Sun%20(USA%2C%20Europe).zip',
        downloadUrl: '${_myrientGba}Golden%20Sun%20(USA%2C%20Europe).zip',
        requiresBrowser: false,
        gameId: 'AGSE',
        fileSizeMb: 8,
        size: '8 MB',
        format: 'ZIP',
        description: 'Epic RPG with Djinn-based combat and stunning GBA visuals.',
      ),
      GameResult(
        title: 'Golden Sun: The Lost Age (USA)',
        platform: 'GBA',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGba}Golden%20Sun%20-%20The%20Lost%20Age%20(USA%2C%20Europe).zip',
        downloadUrl: '${_myrientGba}Golden%20Sun%20-%20The%20Lost%20Age%20(USA%2C%20Europe).zip',
        requiresBrowser: false,
        gameId: 'AGFE',
        fileSizeMb: 16,
        size: '16 MB',
        format: 'ZIP',
        description: 'Continue the journey with new heroes and expanded Psynergy abilities.',
      ),
      GameResult(
        title: 'Castlevania: Aria of Sorrow (USA)',
        platform: 'GBA',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientGba}Castlevania%20-%20Aria%20of%20Sorrow%20(USA).zip',
        downloadUrl: '${_myrientGba}Castlevania%20-%20Aria%20of%20Sorrow%20(USA).zip',
        requiresBrowser: false,
        gameId: 'ACBE',
        fileSizeMb: 8,
        size: '8 MB',
        format: 'ZIP',
        description: 'Soma Cruz collects monster souls in this acclaimed metroidvania.',
      ),

      // === N64 GAMES ===
      GameResult(
        title: 'Super Mario 64 (USA)',
        platform: 'N64',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientN64}Super%20Mario%2064%20(USA).zip',
        downloadUrl: '${_myrientN64}Super%20Mario%2064%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 8,
        size: '8 MB',
        format: 'ZIP',
        description: 'The revolutionary 3D platformer that defined a generation.',
      ),
      GameResult(
        title: 'Legend of Zelda: Ocarina of Time (USA)',
        platform: 'N64',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientN64}Legend%20of%20Zelda%2C%20The%20-%20Ocarina%20of%20Time%20(USA).zip',
        downloadUrl: '${_myrientN64}Legend%20of%20Zelda%2C%20The%20-%20Ocarina%20of%20Time%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 32,
        size: '32 MB',
        format: 'ZIP',
        description: 'The epic adventure that set the standard for 3D Zelda games.',
      ),
      GameResult(
        title: 'Legend of Zelda: Majora\'s Mask (USA)',
        platform: 'N64',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientN64}Legend%20of%20Zelda%2C%20The%20-%20Majora\'s%20Mask%20(USA).zip',
        downloadUrl: '${_myrientN64}Legend%20of%20Zelda%2C%20The%20-%20Majora\'s%20Mask%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 32,
        size: '32 MB',
        format: 'ZIP',
        description: 'A dark, time-bending Zelda adventure with transforming masks.',
      ),
      GameResult(
        title: 'GoldenEye 007 (USA)',
        platform: 'N64',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientN64}GoldenEye%20007%20(USA).zip',
        downloadUrl: '${_myrientN64}GoldenEye%20007%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 12,
        size: '12 MB',
        format: 'ZIP',
        description: 'The legendary FPS that revolutionized console shooters.',
      ),
      GameResult(
        title: 'Mario Kart 64 (USA)',
        platform: 'N64',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientN64}Mario%20Kart%2064%20(USA).zip',
        downloadUrl: '${_myrientN64}Mario%20Kart%2064%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 12,
        size: '12 MB',
        format: 'ZIP',
        description: 'Four-player kart racing mayhem that defined multiplayer gaming.',
      ),
      GameResult(
        title: 'Super Smash Bros. (USA)',
        platform: 'N64',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientN64}Super%20Smash%20Bros.%20(USA).zip',
        downloadUrl: '${_myrientN64}Super%20Smash%20Bros.%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 16,
        size: '16 MB',
        format: 'ZIP',
        description: 'The original crossover fighting game that started a phenomenon.',
      ),
      GameResult(
        title: 'Banjo-Kazooie (USA)',
        platform: 'N64',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientN64}Banjo-Kazooie%20(USA).zip',
        downloadUrl: '${_myrientN64}Banjo-Kazooie%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 16,
        size: '16 MB',
        format: 'ZIP',
        description: 'Rare\'s beloved collect-a-thon platformer with a bear and bird duo.',
      ),
      GameResult(
        title: 'Paper Mario (USA)',
        platform: 'N64',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: '${_myrientN64}Paper%20Mario%20(USA).zip',
        downloadUrl: '${_myrientN64}Paper%20Mario%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 40,
        size: '40 MB',
        format: 'ZIP',
        description: 'The charming RPG where Mario becomes paper-thin to save the day.',
      ),

      // === SNES GAMES ===
      GameResult(
        title: 'Super Mario World (USA)',
        platform: 'SNES',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientSnes,
        downloadUrl: '${_myrientSnes}Super%20Mario%20World%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 1,
        size: '512 KB',
        description: 'The SNES launch title that introduced Yoshi and set new standards.',
      ),
      GameResult(
        title: 'Legend of Zelda: A Link to the Past (USA)',
        platform: 'SNES',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientSnes,
        downloadUrl: '${_myrientSnes}Legend%20of%20Zelda,%20The%20-%20A%20Link%20to%20the%20Past%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 1,
        size: '1 MB',
        description: 'The definitive top-down Zelda adventure with Light and Dark Worlds.',
      ),
      GameResult(
        title: 'Super Metroid (USA)',
        platform: 'SNES',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientSnes,
        downloadUrl: '${_myrientSnes}Super%20Metroid%20(Japan,%20USA)%20(En,Ja).zip',
        requiresBrowser: false,
        fileSizeMb: 3,
        size: '3 MB',
        description: 'The atmospheric masterpiece that defined the metroidvania genre.',
      ),
      GameResult(
        title: 'Chrono Trigger (USA)',
        platform: 'SNES',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientSnes,
        downloadUrl: '${_myrientSnes}Chrono%20Trigger%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 4,
        size: '4 MB',
        description: 'Time-traveling RPG masterpiece from the Dream Team.',
      ),
      GameResult(
        title: 'Final Fantasy VI (USA)',
        platform: 'SNES',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientSnes,
        downloadUrl: '${_myrientSnes}Final%20Fantasy%20III%20(USA)%20(Rev%201).zip',
        requiresBrowser: false,
        fileSizeMb: 3,
        size: '3 MB',
        description: 'Epic RPG with a memorable cast fighting against the mad clown Kefka.',
      ),
      GameResult(
        title: 'Super Mario RPG (USA)',
        platform: 'SNES',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientSnes,
        downloadUrl: '${_myrientSnes}Super%20Mario%20RPG%20-%20Legend%20of%20the%20Seven%20Stars%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 4,
        size: '4 MB',
        description: 'Mario\'s first RPG, developed with Square\'s magic touch.',
      ),
      GameResult(
        title: 'Donkey Kong Country (USA)',
        platform: 'SNES',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientSnes,
        downloadUrl: '${_myrientSnes}Donkey%20Kong%20Country%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 4,
        size: '4 MB',
        description: 'Revolutionary pre-rendered graphics in this platforming classic.',
      ),
      GameResult(
        title: 'EarthBound (USA)',
        platform: 'SNES',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientSnes,
        downloadUrl: '${_myrientSnes}EarthBound%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 3,
        size: '3 MB',
        description: 'The quirky RPG where a boy named Ness saves the world.',
      ),

      // === NES GAMES ===
      GameResult(
        title: 'Super Mario Bros. 3 (USA)',
        platform: 'NES',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientNes,
        downloadUrl: '${_myrientNes}Super%20Mario%20Bros.%203%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 1,
        size: '384 KB',
        description: 'The ultimate NES platformer with world maps and power suits.',
      ),
      GameResult(
        title: 'Legend of Zelda (USA)',
        platform: 'NES',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientNes,
        downloadUrl: '${_myrientNes}Legend%20of%20Zelda,%20The%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 1,
        size: '128 KB',
        description: 'The original adventure that started the legendary series.',
      ),
      GameResult(
        title: 'Mega Man 2 (USA)',
        platform: 'NES',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientNes,
        downloadUrl: '${_myrientNes}Mega%20Man%202%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 1,
        size: '256 KB',
        description: 'The Blue Bomber\'s finest hour with iconic robot masters.',
      ),
      GameResult(
        title: 'Castlevania III: Dracula\'s Curse (USA)',
        platform: 'NES',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientNes,
        downloadUrl: '${_myrientNes}Castlevania%20III%20-%20Dracula\'s%20Curse%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 1,
        size: '384 KB',
        description: 'Trevor Belmont\'s quest with branching paths and allies.',
      ),

      // === GENESIS GAMES ===
      GameResult(
        title: 'Sonic the Hedgehog 2 (USA)',
        platform: 'Genesis',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientGenesis,
        downloadUrl: '${_myrientGenesis}Sonic%20The%20Hedgehog%202%20(World).zip',
        requiresBrowser: false,
        fileSizeMb: 1,
        size: '1 MB',
        description: 'Sonic and Tails\' high-speed adventure through Chemical Plant and beyond.',
      ),
      GameResult(
        title: 'Sonic the Hedgehog 3 & Knuckles (USA)',
        platform: 'Genesis',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientGenesis,
        downloadUrl: '${_myrientGenesis}Sonic%20%26%20Knuckles%20%2B%20Sonic%20The%20Hedgehog%203%20(USA)%20(Lock-on%20Combination).zip',
        requiresBrowser: false,
        fileSizeMb: 4,
        size: '4 MB',
        description: 'The complete Sonic 3 experience with all characters unlocked.',
      ),
      GameResult(
        title: 'Streets of Rage 2 (USA)',
        platform: 'Genesis',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientGenesis,
        downloadUrl: '${_myrientGenesis}Streets%20of%20Rage%202%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 2,
        size: '2 MB',
        description: 'The pinnacle of beat-em-up action with an incredible soundtrack.',
      ),
      GameResult(
        title: 'Gunstar Heroes (USA)',
        platform: 'Genesis',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientGenesis,
        downloadUrl: '${_myrientGenesis}Gunstar%20Heroes%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 1,
        size: '1 MB',
        description: 'Treasure\'s explosive run-and-gun masterpiece.',
      ),

      // === PS1 GAMES ===
      GameResult(
        title: 'Final Fantasy VII (USA)',
        platform: 'PS1',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientPs1,
        downloadUrl: '${_myrientPs1}Final%20Fantasy%20VII%20(USA)%20(Disc%201).zip',
        requiresBrowser: false,
        fileSizeMb: 500,
        size: '500 MB',
        format: 'ZIP',
        description: 'The legendary RPG that brought JRPGs to the mainstream. (Disc 1)',
      ),
      GameResult(
        title: 'Castlevania: Symphony of the Night (USA)',
        platform: 'PS1',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientPs1,
        downloadUrl: '${_myrientPs1}Castlevania%20-%20Symphony%20of%20the%20Night%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 500,
        size: '500 MB',
        format: 'ZIP',
        description: 'Alucard explores Dracula\'s castle in this genre-defining classic.',
      ),
      GameResult(
        title: 'Metal Gear Solid (USA)',
        platform: 'PS1',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientPs1,
        downloadUrl: '${_myrientPs1}Metal%20Gear%20Solid%20(USA)%20(Disc%201).zip',
        requiresBrowser: false,
        fileSizeMb: 800,
        size: '800 MB',
        format: 'ZIP',
        description: 'Solid Snake\'s legendary stealth mission. (Disc 1)',
      ),
      GameResult(
        title: 'Resident Evil 2 (USA)',
        platform: 'PS1',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientPs1,
        downloadUrl: '${_myrientPs1}Resident%20Evil%202%20(USA)%20(Disc%201).zip',
        requiresBrowser: false,
        fileSizeMb: 700,
        size: '700 MB',
        format: 'ZIP',
        description: 'Survive the Raccoon City outbreak. (Disc 1 - Leon)',
      ),
      GameResult(
        title: 'Crash Bandicoot 3: Warped (USA)',
        platform: 'PS1',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientPs1,
        downloadUrl: '${_myrientPs1}Crash%20Bandicoot%20-%20Warped%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 450,
        size: '450 MB',
        format: 'ZIP',
        description: 'Time-traveling platforming with the orange marsupial.',
      ),

      // === NDS GAMES ===
      GameResult(
        title: 'Pokemon HeartGold (USA)',
        platform: 'NDS',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientNds,
        downloadUrl: '${_myrientNds}Pokemon%20-%20HeartGold%20Version%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 128,
        size: '128 MB',
        description: 'The beloved Gen 2 remake with the Pokewalker accessory.',
      ),
      GameResult(
        title: 'Mario Kart DS (USA)',
        platform: 'NDS',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientNds,
        downloadUrl: '${_myrientNds}Mario%20Kart%20DS%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 32,
        size: '32 MB',
        description: 'Portable kart racing with online play and retro tracks.',
      ),
      GameResult(
        title: 'New Super Mario Bros. (USA)',
        platform: 'NDS',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientNds,
        downloadUrl: '${_myrientNds}New%20Super%20Mario%20Bros.%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 64,
        size: '64 MB',
        description: 'The 2D Mario revival that sparked a new sub-series.',
      ),

      // === PSP GAMES ===
      GameResult(
        title: 'God of War: Chains of Olympus (USA)',
        platform: 'PSP',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientPsp,
        downloadUrl: '${_myrientPsp}God%20of%20War%20-%20Chains%20of%20Olympus%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 1200,
        size: '1.2 GB',
        format: 'ZIP',
        description: 'Kratos\' brutal adventure before the original God of War.',
      ),
      GameResult(
        title: 'Monster Hunter Freedom Unite (USA)',
        platform: 'PSP',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientPsp,
        downloadUrl: '${_myrientPsp}Monster%20Hunter%20Freedom%20Unite%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 1500,
        size: '1.5 GB',
        format: 'ZIP',
        description: 'Hunt massive monsters in this addictive action RPG.',
      ),
      GameResult(
        title: 'Crisis Core: Final Fantasy VII (USA)',
        platform: 'PSP',
        region: 'USA',
        provider: 'Myrient',
        pageUrl: _myrientPsp,
        downloadUrl: '${_myrientPsp}Crisis%20Core%20-%20Final%20Fantasy%20VII%20(USA).zip',
        requiresBrowser: false,
        fileSizeMb: 1800,
        size: '1.8 GB',
        format: 'ZIP',
        description: 'Zack Fair\'s story as a SOLDIER before the events of FF7.',
      ),
    ];
  }

  /// Get cover art URL from GameTDB
  static String getCoverUrl(String gameId,
      {String type = 'cover3D', String platform = 'wii'}) {
    // GameTDB URL format varies by platform
    final platformPath = platform.toLowerCase() == 'gamecube'
        ? 'gamecube'
        : platform.toLowerCase() == 'wii u'
            ? 'wiiu'
            : 'wii';
    return 'https://art.gametdb.com/$platformPath/$type/EN/$gameId.png';
  }
}

/// Myrient Provider - real directory listing search via MyrientService
class MyrientProvider implements SearchProvider {
  @override
  String get name => 'Myrient';

  static final _myrient = MyrientService();

  @override
  Future<List<GameResult>> search(String query, {String? platform}) async {
    final results = await _myrient.search(query);
    if (platform == null || platform.isEmpty) return results;
    final lower = platform.toLowerCase();
    return results
        .where((r) => r.platform.toLowerCase().contains(lower))
        .toList();
  }
}

/// RomsGames Provider (requires browser automation)
class RomsGamesProvider implements SearchProvider {
  @override
  String get name => 'RomsGames';

  @override
  Future<List<GameResult>> search(String query, {String? platform}) async {
    final allResults = [
      GameResult(
        title: 'Wii Sports (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: name,
        pageUrl: 'https://www.romsgames.net/nintendo-wii-rom-wii-sports/',
        requiresBrowser: true,
        gameId: 'RSPE01',
        fileSizeMb: 350,
      ),
      GameResult(
        title: 'New Super Mario Bros. Wii (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/nintendo-wii-rom-new-super-mario-bros-wii/',
        requiresBrowser: true,
        gameId: 'SMNE01',
        fileSizeMb: 4000,
      ),
      GameResult(
        title: 'Mario Kart Wii (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: name,
        pageUrl: 'https://www.romsgames.net/nintendo-wii-rom-mario-kart-wii-1/',
        requiresBrowser: true,
        gameId: 'RMCE01',
        fileSizeMb: 4700,
      ),
      GameResult(
        title: 'Dragon Ball Z: Budokai Tenkaichi 3 (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/nintendo-wii-rom-dragon-ball-z-budokai-tenkaichi-3-1/',
        requiresBrowser: true,
        gameId: 'RDSE70',
        fileSizeMb: 4300,
      ),
      GameResult(
        title: 'Super Mario Galaxy (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/nintendo-wii-rom-super-mario-galaxy-1/',
        requiresBrowser: true,
        gameId: 'RMGE01',
        fileSizeMb: 4400,
      ),
      GameResult(
        title: 'Legend of Zelda, The: Skyward Sword (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/nintendo-wii-rom-legend-of-zelda-the-skyward-sword/',
        requiresBrowser: true,
        gameId: 'SOUE01',
        fileSizeMb: 4700,
      ),
      GameResult(
        title: 'Super Mario Galaxy 2 (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/nintendo-wii-rom-super-mario-galaxy-2-1/',
        requiresBrowser: true,
        gameId: 'SB4E01',
        fileSizeMb: 1300,
      ),
      GameResult(
        title: 'Resident Evil 4: Wii Edition (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/nintendo-wii-rom-resident-evil-4-wii-edition-1-1/',
        requiresBrowser: true,
        gameId: 'RB4E08',
        fileSizeMb: 4100,
      ),
      GameResult(
        title: 'Xenoblade Chronicles (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/nintendo-wii-rom-xenoblade-chronicles/',
        requiresBrowser: true,
        gameId: 'SX4E01',
        fileSizeMb: 6500,
      ),
      GameResult(
        title: 'Kirby\'s Return to Dream Land (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/nintendo-wii-rom-kirbys-return-to-dream-land/',
        requiresBrowser: true,
        gameId: 'SUKE01',
        fileSizeMb: 1200,
      ),
      GameResult(
        title: 'Animal Crossing: City Folk (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/nintendo-wii-rom-animal-crossing-city-folk/',
        requiresBrowser: true,
        gameId: 'RUUE01',
        fileSizeMb: 350,
      ),

      // === GAMECUBE GAMES ===
      GameResult(
        title: 'Super Smash Bros. Melee (USA)',
        platform: 'GameCube',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/gamecube-rom-super-smash-bros-melee/',
        requiresBrowser: true,
        gameId: 'GALE01',
        fileSizeMb: 1400,
      ),
      GameResult(
        title: 'Legend of Zelda: Wind Waker (USA)',
        platform: 'GameCube',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/gamecube-rom-legend-of-zelda-wind-waker/',
        requiresBrowser: true,
        gameId: 'GZLE01',
        fileSizeMb: 1400,
      ),
      GameResult(
        title: 'Mario Kart: Double Dash!! (USA)',
        platform: 'GameCube',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/gamecube-rom-mario-kart-double-dash/',
        requiresBrowser: true,
        gameId: 'GM4E01',
        fileSizeMb: 1400,
      ),
      GameResult(
        title: 'Super Mario Sunshine (USA)',
        platform: 'GameCube',
        region: 'USA',
        provider: name,
        pageUrl: 'https://www.romsgames.net/gamecube-rom-super-mario-sunshine/',
        requiresBrowser: true,
        gameId: 'GMSE01',
        fileSizeMb: 1400,
      ),
      GameResult(
        title: 'Metroid Prime (USA)',
        platform: 'GameCube',
        region: 'USA',
        provider: name,
        pageUrl: 'https://www.romsgames.net/gamecube-rom-metroid-prime/',
        requiresBrowser: true,
        gameId: 'GM8E01',
        fileSizeMb: 1400,
      ),
      GameResult(
        title: 'Paper Mario: Thousand-Year Door (USA)',
        platform: 'GameCube',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/gamecube-rom-paper-mario-thousand-year-door/',
        requiresBrowser: true,
        gameId: 'G8ME01',
        fileSizeMb: 1400,
      ),
      GameResult(
        title: 'Super Mario Galaxy (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/nintendo-wii-rom-super-mario-galaxy-1/',
        requiresBrowser: true,
        gameId: 'RMGE01',
        fileSizeMb: 4400,
      ),
      GameResult(
        title: 'Legend of Zelda, The: Skyward Sword (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/nintendo-wii-rom-legend-of-zelda-the-skyward-sword/',
        requiresBrowser: true,
        gameId: 'SOUE01',
        fileSizeMb: 4700,
      ),
      GameResult(
        title: 'Super Mario Galaxy 2 (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/nintendo-wii-rom-super-mario-galaxy-2-1/',
        requiresBrowser: true,
        gameId: 'SB4E01',
        fileSizeMb: 1300,
      ),
      GameResult(
        title: 'Resident Evil 4: Wii Edition (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/nintendo-wii-rom-resident-evil-4-wii-edition-1-1/',
        requiresBrowser: true,
        gameId: 'RB4E08',
        fileSizeMb: 4100,
      ),
      GameResult(
        title: 'Call of Duty: Modern Warfare 3 (USA)',
        platform: 'Wii',
        region: 'USA',
        provider: name,
        pageUrl:
            'https://www.romsgames.net/nintendo-wii-rom-call-of-duty-modern-warfare-3/',
        requiresBrowser: true,
        gameId: 'SM3E52',
        fileSizeMb: 4300,
      ),
    ];

    final queryLower = query.toLowerCase();
    return allResults
        .where((r) => r.title.toLowerCase().contains(queryLower))
        .toList();
  }
}
